import fs from "node:fs/promises";
import { glob } from "glob";
import type { Config } from "./config";
import { extractCssVars } from "./extractCssVars";
import { generateCode } from "./generateCode";

export const generator = async (config: Config) => {
    const files = await Promise.all(
        config.directories.map((directory) => glob(`${directory}/*.css`)),
    );
    const cssVars = await Promise.all(
        files
            .flat()
            .map((file) => fs.readFile(file, "utf-8"))
            .map((content) => content.then(extractCssVars)),
    );
    const code = generateCode(Object.assign({}, ...cssVars));
    await fs.writeFile(
        config.output,
        // biome-ignore lint/style/useTemplate: <explanation>
        [
            ...config.fileHeader,
            "// This file is auto-generated by css-var-extract",
            code
                ? code
                : [
                      "// !! Warning: not found css vars",
                      "// Please check files option in cve.config.json",
                  ].join("\n"),
            ...config.fileFooter,
        ].join("\n\n") + "\n",
        "utf-8",
    );
};
