import type { CssVars } from "./types";

const generateCode = (cssVars: CssVars): string => {
    const output = [];
    output.push(
        "/* prettier-ignore-start */",
        "",
        "/* eslint-disable */",
        "",
        "// noinspection JSUnusedGlobalSymbols",
        "",
        "// This file is auto-generated by css-var-extract",
    );
    for (const [name, values] of Object.entries(cssVars)) {
        output.push("");
        for (const [condition, value] of Object.entries(values)) {
            if (condition) {
                output.push(`// ${condition}: ${value}`);
            } else {
                output.push(`// ${value}`);
            }
        }
        output.push(
            `export const ${name.substring(2).replaceAll("-", "_")} = "var(${name})"`,
        );
    }
    output.push("", "/* prettier-ignore-end */");
    return output.join("\n");
};

export default generateCode;
